### ISSUE TITLE
How can I run the tests?

### ISSUE THREAD

**Issue by bertolo1988** [stayawayinesctec/stayaway-app#3]
title.

**Comment by gui-com-pt** [comment]
I was also looking for it. Don't this app have any tests?!

**Comment by NSMyself** [comment]
There doesn’t seem to be any 😞 quite astounding if we consider the importance of this app...

**Comment by fmcruz** [comment]
We are aware of the importance of tests, thus we used RN packages that have good coverage, in particular the DP3T server and SDKs have tests themselves that you can run. Nonetheless, PRs are very welcome.

**Comment by tsbatista** [comment]
@fmcruz Im not sure what are your concepts of code quality, but if as a professional developer I were utter that sentence as an attempt to justify my incompetence, I would be fired on the spot! The fact that the framework is well tested does not preclude your application from introducing bugs and regressions with every commit. Show some respect for your users and spend a couple of days properly covering your code with unit tests!

**Comment by mluisbrown** [comment]
@tsbatista there is no need to be so harsh, or be calling anyone "incompetent" 😕 

However:
> The fact that the framework is well tested does not preclude your application from introducing bugs and regressions with every commit.

This is 💯  correct. You have to test your own code, not just rely on tested frameworks. For a government sponsored app with such critical requirements, that might well save lives, it is absolutely vital that the code is well tested.

**Comment by franciscofsales** [comment]
There is a large enough pool of plausible reasons for the code to not be properly clean or even tested.. such as tight deadlines, the small codebase (thus less effective possibility of tech debt), political pressure, and so on.. all but undermining the importance of proper testing and software engineering practices. And furthermore, it was a great opportunity to state on the readme as something that the community could contribute on, I mean, that's one of the main benefits of open source.

Stating that dependencies are well tested and have good coverage is only reasonable in a scenario where the project is purely libraries, I, personally, do not know a single one like that. On top of that, some of the RN dependencies used are not even tested, so the part of the good coverage, I mean, the RN community ones are generally decently covered, but the other ones are iffy, to say the least.

Yeah, I realize that would be mostly the frontend of the app since it heavily relies on the DP-3T SDK, but again since the codebase is small and the app is not that extensive, would it really be such a tremendous effort considering the criticalness of the app?

**Comment by bertolo1988** [comment]
> We are aware of the importance of tests, thus we used RN packages that have good coverage, in particular the DP3T server and SDKs have tests themselves that you can run. Nonetheless, PRs are very welcome.

I was looking for functional, unit tests, e2e tests, not dependency tests. 
For those I can just look at the dependency tree and look for the projects online.

**Comment by mluisbrown** [comment]
> Considering the tight deadline I would have never picked react-native for this project. A simple responsive web-app would have been much simpler and faster to develop.

It's not possible to use the native Apple / Google exposure notification frameworks from a responsive web-app. Also I very much doubt that a PWA would be any faster to develop.

**Comment by piresbruno** [comment]
Criticizing is easy, building products is hard.
It would be very healthy if we have more than one app available to the public, that would only benefit everyone, so instead of being negative, we (community) should either contribute to improve or build something better.

**Comment by gitnewcomer** [comment]
> It would be very healthy if we have more than one app available to the public, that would only benefit everyone, so instead of being negative, we (community) should either contribute to improve this one or build something better.

The German App was already published to the public more than a month ago and have been downloaded by over 16 million people. So why don't we fork it and translate it to portuguese (english and german is already built in, so it is also great for the tourists visiting us)? We don't need to invent the wheel again! Why not cooperate with the german project (developed by the big SAP company) providing bug fixes found on the portuguese reality?...
Here is the complete open source code for the project (homepage, server, android and ios app), let's translate it an publish it as soon as possible (as sooner we get an app, sooner we can save lives): https://github.com/corona-warn-app

**Comment by bertolo1988** [comment]
> Criticizing is easy, building products is hard.

Criticizing is also a contribution.

**Comment by franciscofranco** [comment]
Always test in production 👍

**Comment by tsbatista** [comment]
@piresbruno notice that I did not say a word before the issue was closed. I would not have said anything if the developer himself would have said that he did not have time to implement the tests and either kept this issue open, or opened another one clearly stating that the app is not covered by unit tests, after all we all know that lack of tests unit or other types IS an issue.

@fmcruz Tis concerns you directly: What triggered me as both a software developer and as a stakeholder is that the person that  replied has not contributed with a single commit so he is clearly the "boss", I read the comment and saw an excuse that maybe can stick in a political report... It looks that this app is being developed as a student project or something very close to that (maybe a grant), so this IS also a situation where the most graduated person the "boss" that actually holds a Phd in computer science should take it as an opportunity to show the person under his wing how to manage software projects. In the event that one of the limiting factors (time, money, quality - choose two) actually limits the quality of the initial output, it would be his job to tell the developer: See, in this event, you will actually acknowledge there is an issue, open a well formatted issue, and link it here before closing this one (as it is actually malformed).

So I stand by my initial assessment closing this issues with that excuse showed lack of competence in project management - hence incompetence (the correct word for an error like this). The good news is that I also expect this to be a learning experience, incompetence is not a natural state, in this case I assume it results from lack of knowledge - I am aware that this is probably the first time for both of them developing an open source project, possibly even the first time developing out of the academic realm. My advice - which I should not need to give:

1. Try to figure what went wrong on your first issue
2. Never give a political excuse to an engineer, it will come out as insulting their intelligence
3. Let the contributors manage their own issues, that is how they will grow

On a more technical side, implement a couple of unit tests, ensure they run on CI/CD, and link the bage to the README and PRs, once you have that, the community will see you have tests and that you use them, so they will maybe contribute with new tests. They will not come in if they are not used as a gatekeeper of production deployments!

**Comment by sdsantos** [comment]
> > It would be very healthy if we have more than one app available to the public, that would only benefit everyone, so instead of being negative, we (community) should either contribute to improve this one or build something better.
> 
> The German App was already published to the public more than a month ago and have been downloaded by over 16 million people. So why don't we fork it and translate it to portuguese (english and german is already built in, so it is also great for the tourists visiting us)? We don't need to invent the wheel again! Why not cooperate with the german project (developed by the big SAP company) providing bug fixes found on the portuguese reality?...
> Here is the complete open source code for the project (homepage, server, android and ios app), let's translate it an publish it as soon as possible (as sooner we get an app, sooner we can save lives!): https://github.com/corona-warn-app
> Just check all the professional and detailed documentation they have on the project page...

This app was also based on existing native Android and iOS apps (https://github.com/DP-3T/dp3t-app-ios-ch and https://github.com/DP-3T/dp3t-app-android-ch), including re-using some of their code. So a port of those apps would definitely be a possibility.

**Comment by gitnewcomer** [comment]
> This app was also based on existing native Android and iOS apps (https://github.com/DP-3T/dp3t-app-ios-ch and https://github.com/DP-3T/dp3t-app-android-ch), including re-using some of their code. So a port of those apps would definitely be a possibility.

The German law is very strict with privacy data, so I think that the complete solution could be used (server and client side) and would probably pass the tests from CNPD.
The advantage using this solution is that the early problems that have been found are already been fixed, being the last critical one the problem on Huawei (Honor) smartphones, where the battery optimization implemented by Huawei where not permitting the app to function correctly. One think that we can not use is the app icon, because it is copyrighted by the German government, but this is a minor problem, because we already have a name and icon for the app.
Like I already told, we don't need to reinvent the wheel and we should not be ashamed using the German project as our code base, this is why it is open source code! What matters here is saving lives, so just let us use tools that are almost ready to use... :)

**Comment by JoaoTMDias** [comment]
> We are aware of the importance of tests, thus we used RN packages that have good coverage, in particular the DP3T server and SDKs have tests themselves that you can run. Nonetheless, PRs are very welcome.

First of all, thank you for sharing the code for everyone to check it out. 

Now, while I understand your point of view, I disagree. 

The point of writing tests for your app is for them to pass regardless of your repo or someone else's. It is a certainty that the code you wrote, no matter how little, does not prevent your tests from passing and that your objectives are met.

Yes, some libraries do have good test coverage, but that's totally not the point here. Your objectives are totally different that the creators of said libraries. 

So yes, you should have spent a little time investing on, at least, unit testing. Perhaps end-to-end as well.

But it's not too late. You can start with Jest and @testing-library for react native, that will help you on your path. See if you can use Cypress, Appium or Detox for your end-to-end testing.

If you're not able to write as many tests as you would like, please provide a document what you would like have covered and perhaps we (speak for myself) can help you out.

Good luck 👍

P.S: please be kind to each other whilst providing feedback, there's no need to behave in such rude manner. Try to help, not to belittle the work that has been done. It is important that we have these projects, regardless if they don't have tests yet.

**Comment by PedroD** [comment]
@fmcruz for a project that cost the Portuguese citizens €400,000, an answer like that is a shame for your country, career and INESC.

In any other place you would be fired on the spot.

We understand if the timelines are short and if the team started outnumbered by the challenges you faced. But dismissing tests for a health-related app as not important and the final touch "Nonetheless, PRs are very welcome 🍒" is just like saying "you want them, you do it", like if €400K is not enough. At least you could have included this need on a README for the community contributing to this project (for free) know that this is an urgent task.

As a former researcher in INESC, I hope people within this very world-wide reputable organization learn from this mistake. This is not a technical mistake, this is a bad/arrogant attitude mistake.

> We are aware of the importance of tests, thus we used RN packages that have good coverage, in particular the DP3T server and SDKs have tests themselves that you can run.

I'll just end with this, as everything else was already said by the other members here.: Stating that you don't need to do tests because your frameworks/libraries have tests, is like saying you added no new code/value/functionalities to them, which means, why the hell did the Portuguese people spend €400K on this for no added value?

Well, everyone makes mistakes, all of us, this is just one, I just hope we all learn.

Best of luck with the project.

**Comment by falkTX** [comment]
Just noticed this issue.. the lack of unit tests is really crucial. Can we reopen? or perhaps best to create a new ticket so we leave this discussion aside..?

**Comment by marado** [comment]
Hi @falkTX, this issue was reopened in #7 , then fixed with #66 .

**Comment by bertolo1988** [comment]
Well done.
