### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by marado** [stayawayinesctec/stayaway-app#52]
Hi there,

For the currently tagged versions in this repository, we have:

* v1.0.0-alpha - Aug 21
* v1.0.0 - Sep 1

This situation is confusing, since on Google's Play Store, the version available is:
* 1.0.0 - August 21, 2020

Naming the "new version" (released yesterday) as 1.0.0 is misleading, as users will think that the version they're using currently from the app stores corresponds this repo's "v1.0.0", when in fact it is "v1.0.0-alpha".

**Comment by djcouto** [comment]
Hello @marado,

There was a problem with the tag `v1.0.0-alpha` because it should be tagged as alpha, it should not be named `v1.0.0`.
When I tried to rename it, I ended up accidentally creating a new release.
We agree that versioning is important and it should match the play store's versions.
This is now fixed, thank you for calling our attention to this 👍 

Closing this issue.
