### ISSUE TITLE
Low contrast on bottom Android bar

### ISSUE THREAD

**Issue by dialex** [stayawayinesctec/stayaway-app#55]
This app changes the Android bottom bar's colour from Black to White, making it very hard to distinguish the white Android navigation buttons. We should change it to some other colour, like `#1d3787` which is one of this app's main colours.

![Screenshot_20200904-184318](https://user-images.githubusercontent.com/2140450/92305240-6143b880-ef7d-11ea-8cba-e42d6670569d.png)

Should I try to make a PR with this change?

**Comment by djcouto** [comment]
@dialex Thank you for pointing out this issue.

TTBOMK there is no native way that you can change the colour of the navigation bar buttons.
What you can change is the navigation bar background colour, which for currently is `#FFFFFF`, and change the theme between dark and light mode.

With that being said, the navigation bar should be looking like this:
<image src="https://user-images.githubusercontent.com/17494742/92398924-5033ac80-f121-11ea-8635-976f6ee4835b.png" height="200" />

I don't know the reason why you are getting a different looking navigation bar, but I suspected that it has something to do your operating system not recognizing the flag `windowLightNavigationBar`.

I'm willing to consider removing this flag and go back to default navigation bar colours (black and white), but I would like to know more about this before. 

Can you please please check what's the reason for your weird navigation bar design?

**Comment by dialex** [comment]
> _change is the navigation bar background colour_

Right, that's what I meant, the bar not the buttons, sorry for the confusion 😅 

It's probably because of my Android version then. I'm using Marshmallow 6.0 (Kernel version 3.4.41-g0a0ded4) on a Moto G2. Likely my version doesn't support Dark/Light themes and doesn't have that bar.

Maybe this helps, it sounds fairly similar: https://stackoverflow.com/questions/55173211/android-windowlightnavigationbar-not-working

**Comment by filipebatista** [comment]
I believe this has to do with `android:navigationBarColor` https://github.com/stayawayinesctec/stayaway-app/blob/ff885b9c1a5b44e8c03e5928fcf9ec31215907fa/android/app/src/main/res/values/styles.xml#L19
https://developer.android.com/reference/android/view/Window#attr_android:navigationBarColor

**Comment by djcouto** [comment]
I run the app on a Nexus 6 with API 23 (Android 6) simulator and I'm still not able to reproduce this behaviour. 

@dialex can you please check if your suggestion or @filipebatista's, solve your issue?

**Comment by filipebatista** [comment]
@djcouto the issue is reproducible . Just tried a Nexus 5x with API23 

![image](https://user-images.githubusercontent.com/1062959/92414076-93eedc00-f14a-11ea-86ac-bd6b75e3a7ce.png)

**Comment by djcouto** [comment]
@filipebatista thank you, I was able to reproduce this thanks to your suggestion.

I figure out what's happening and what are our options here.
The problem relies on [windowLightNavigationBar](https://developer.android.com/reference/android/R.attr.html#windowLightNavigationBar) attribute has only been added on API Level 27.
What's is happening is that background colour correctly changes to `#FFFFFF`, but since this attribute is not available the navigation buttons colour stays with the default value, causing that low contrast that you experienced.

We don't have many options here since the only thing we can change, for devices with < API 27, is the navigation bar background colour or make this bar translucent.

On the left a translucent and on the right the default one with a black background.

<div>
<image src="https://user-images.githubusercontent.com/17494742/92462628-a147ad00-f1c2-11ea-96a8-009b2d68708e.png" height="150" />
<image src="https://user-images.githubusercontent.com/17494742/92462643-a6a4f780-f1c2-11ea-8691-6722b984cb4a.png" height="150" />
</div>


After showing the solutions to the design team, we will follow the default black background approach.
