### ISSUE TITLE
iOS app doesn't build

### ISSUE THREAD

**Issue by mluisbrown** [stayawayinesctec/stayaway-app#6]
I followed the installation steps and when running `yarn ios-ui` I get the following error:

```
❌  ld: library not found for -lappcenter-analytics

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I notice that CI (GitHub actions) is only running for the Android build. It should be running for iOS too.

**Comment by djcouto** [comment]
Hi @mluisbrown and thank you for opening this issue!

The error is due to a bad linking of the `appcenter-analytics` dependency on iOS, and which your PR correctly solves 👍 

I just want to call your attention to the fact that you'll not be able to run the development app, since for that it requires the `com.apple.developer.exposure-notification` entitlement to be granted by Apple. With that being said you should run UI version with no problem, and if you have any problem with that please let me know.

Regarding the CI aspect, you're absolutely right and we will implement the iOS build pipeline in the future. We are just waiting for the final provisioning profiles and entitlements to be ready.
