### ISSUE TITLE
Implement software tests

### ISSUE THREAD

**Issue by marado** [stayawayinesctec/stayaway-app#7]
On #3 , the issue was closed after the develpment team said that there is no way to run the tests since there are no tests to be run, but that PRs implementing tests are welcome.

Discussion went on in that issue, after it was closed, but I'm opening this one in the hopes that the efforts regarding the implementation of software tests can be focused here.

I take also the opportunity to kindly request this issue not to be closed while those tests aren't implemented: while they might not be a current priority, their importance seems undeniable.

**Comment by gsilvapt** [comment]
If in doubt of their importance, remember you have 248 low vulnerabilities from npm dependencies. Your pipeline should contain a step to audit & fix. The npm ecosystem is known to be horrible in this regard but a single app can follow sane and safer principles.

But automatically fixing npm dependencies is only possible when there are unit tests, otherwise you don't know if things broke due to API changes.

**Comment by maghuro** [comment]
rest assured that withouth them, StayAway app will be ready, fully tested and totally operational when the 2120 pandemic arrives.

**Comment by fmaia** [comment]
A test suite as been added to the project. Please consider closing this issue.
