### ISSUE TITLE
Support older iOS versions

### ISSUE THREAD

**Issue by bopinto** [stayawayinesctec/stayaway-app#70]
There are many people with old iPhones, that can’t update to iOS version 13.5.
The app should be inclusive also in that sense.

**Comment by davipt** [comment]
Note: this is my personal opinion and I do not belong to the dev team

This app, like other similar apps, relies on the operating system's exposure notification API, which is only available on iOS 13.5 and later. This means all iPhones since the 6S and SE from 2015.

To support older devices, namely the 6 (2014) and 5S (2013), Apple would have to add themselves the exposure notification to iOS 12, which would not be unthinkable, as they've been updating that old version with security fixes, but it's highly improbable. Also, I'm not sure the 5S with only Bluetooth 4.0 would be suitable for this feature.

You can help the community and give that feedback to Apple (https://www.apple.com/feedback/iphone.html) but don't have high hopes with that.

**Comment by bopinto** [comment]
Yeah... I searched a bit about this and got to the same conclusion... It's unfortunate...
If this is the exposure API is the only limitation, I'm happy to close this issue.

**Comment by davipt** [comment]
The exposure API is a core component, not for the exposure management and notifications themselves, but for the delegation of the management of the bluetooth communication to the operating system, in an consistent and energy efficient way, without the need to either expose low level bluetooth functionality (which would be dangerous for security and privacy reasons), nor the need to have the app always open and in the foreground like others have attempted to, with no success.
I suspect if Apple would attempt to also support the older 5S and 6 they would go the way of Android, where theoretically there is support for any Android 5.0 or later as long as they are able to update the Google Mobile Services system components, but in practice many of those devices won't have the necessary bluetooth capabilities, or allow an efficient battery management (there is another ticket here about this one), making it harder for the developers and the users to know if the functionality will work or not.

**Comment by fmaia** [comment]
Hi @bopinto and @davipt , thank you for bringing this discussion up and for the "straight to the point" information you gathered 👍

**Comment by RuiAAPeres** [comment]
Maybe close this issue?
