### ISSUE TITLE
Version 1.0.4 automatically disables exposure monitoring on iOS

### ISSUE THREAD

**Issue by atmcarmo** [stayawayinesctec/stayaway-app#74]
Hi,

My iPhone (on iOS 14.0.1) updated the app to version 1.0.4 and the app automatically disabled exposure monitoring. It shows that the latest risk evaluation was today (before the update) and now monitoring is just disabled without my interaction.

I've discovered some other people with the exact same situation. I think this is a major issue that may case many people to have exposure monitoring disabled, which compromises the effectiveness of this app.

I'm available for more details if needed.

**Comment by davipt** [comment]
I can confirm this. 
Last update yesterday morning, according to iOS settings.  
App was updated yesterday afternoon. 
Settings says the state is active and DGS is the region, all normal there. 
Starting the app shows "rastreio não está activo" in blue. Touching it quickly switches to the green active screen, and immediately updates from the server. 

This looks like the app asking the system if EN is enabled, which is, but thinking otherwise, and thus not updating data in the background. 
Upon opening the app and following the flow to enable the EN, which I think it would even switch to iOS settings (maybe not?). 

Wasn't there a bump on the EN version within the dp3t library?

**Comment by fmaia** [comment]
Thank you for opening this issue! We have identified a problem handling the case where an exposure check is not possible due to the check limit imposed by the EN API. This may happen when updating. This bug leads the app to believe monitoring to be disabled. We are working on a patch for this and will release it asap.

**Comment by fmaia** [comment]
Version 1.0.5 for iOS was released. Could you try the update and check if this behaviour has been fixed? Thank you

**Comment by atmcarmo** [comment]
Hi @fmaia. Updated and it seems to have been fixed, however I had already turned monitoring on before. My concern is for people that have not manually turned on monitoring while updating to 1.0.4.

This issue can be closed.

**Comment by fmaia** [comment]
Thank you for the feedback. Version 1.0.5 will fix that issue if the user has the operating system Exposure Notification information sharing on.
