### ISSUE TITLE
Problem trying to run on Lineage OS

### ISSUE THREAD

**Issue by vbuaraujo** [stayawayinesctec/stayaway-app#86]
Hello, everyone!

I'm aware that this use case is not likely a priority, but I tried to run the app on Lineage OS 14.1 (Android 7.1), and I cannot turn on monitoring. The app shows a "Monitoring disabled" popup, but the "Enable monitoring" button does nothing. In the settings, "Monitoring" is shown as "Disabled", but when I click on the switch, it momentarily goes grey and then stays off. I have enabled Bluetooth but it did not make a difference.

Do you know what may be causing this, or any pointers on how can I debug what is going on? 

Thanks in advance!

**Comment by fmaia** [comment]
Hi, Lineage OS comes without Google Services pre-installed and these are a requirement for STAYAWAY COVID. In order to run the app you will need the Exposure Notification component from Google. Please check if it is possible to install it in your Lineage OS. 
For additional technical support please contact stayaway@inesctec.pt 

PS: I'm closing this issue because it seems to be an issue with the OS but feel free to reopen if you feel there's more to it. Thank you.

**Comment by falkTX** [comment]
Other applications are slowly starting to support alternative non-googled versions of that API.
But as this one is yet another frontend implementation, efforts will need to be duplicated in order to support it here too.
See also #82 for which we are still waiting an official answer for.

**Comment by fmaia** [comment]
Could you point me to the applications which are supporting other non-GAEN versions of the API and are not national-specific implementations of a contact tracing system? Thank you.

**Comment by falkTX** [comment]
From what I understood https://github.com/CoraLibre/CoraLibre-android-sdk is where most development is happening.
microG has started something, and that one is often used as a drop-in replacement to google services (with limited functionality, as expected)

Recently google opened up the full contract tracing API, so I am not sure what is the current overall status at the moment.

**Comment by fmaia** [comment]
Thank you for the pointer. We are aware of these efforts for creating an alternative API. I was wondering if you saw this implemented in any application in production. To provide some context, DP3T had already proposed (and made available) a non-GAEN API. In Portugal, we integrated this API and ran the initial STAYAWAY COVID tests with it. However, running a standard BLE app has a number of limitations due to battery management. In particular, limitations with background usage which impair their use as a contact tracing app. That is why DP3T moved to adopt GAEN.

**Comment by falkTX** [comment]
Makes sense, thanks.
Though I am really not the best person to ask about the current status of alternatives, I only researched a bit in an attempt to find something that works for me.
I own 2 smartphones - a non-googled android similar to lineageos and a pinephone - and I cannot install stayaway in neither of them :(

as there have been some talks/rumors about requiring stayaway to enter some places, I fear this is going to become a real problem.

**Comment by fmaia** [comment]
We understand the concerns. The choice for GAEN was made to reach the great majority of devices but, as with any technology, has its limitations...

**Comment by weirdNox** [comment]
For what it's worth, I try to use STAYAWAY with MicroG. 

I believe it mostly works; however, an update some weeks ago (1.0.3?) makes the app hang when starting. 
As a workaround, I found that if I disable the Exposure Notification API in MicroG before starting, the app will ask if I want to enable it, and then correctly proceed to the main menu.

Even with this problem, I _believe_ STAYAWAY is working in background, as it asks me to enable Bluetooth if I disable it, and  MicroG shows some contact tracing activity in their settings. I could be wrong, though!

(Off topic: Thanks @falkTX, I had no idea Cadence and significant parts of Jack were being developed by a Portuguese!)

**Comment by falkTX** [comment]
There are some news on this https://fsfe.org/news/2020/news-20201208-01.en.html

**Comment by marado** [comment]
The open issue https://github.com/stayawayinesctec/stayaway-app/issues/34#issuecomment-740485710 has a reference to the implementation the previous comment refers to.
